FROM node:alpine


ARG MONGO_USERNAME
ARG MONGO_PASSWORD
ARG MONGO_DB_NAME
ARG SERVER_PORT

# setup working directory
WORKDIR /app
# copy and install dependencies
COPY ./package*.json ./
RUN npm i

# copy all items into working directory
COPY . .
# expose this images port
EXPOSE 8080
# start backend server
CMD ["npm", "start"]