name: Deployment From Github to AWS Elastic Beanstalk
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest changes in master branch
        uses: actions/checkout@master

      - name: Generate Deployment Package
        # EBS takes in a ZIP file to place inside an S3 bucket.
        # ZIP all files recursively (-r) then call the zip file 'deploy.zip'
        # Copy everything inside (*), but exclude (-x) all node_modules
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: inlimbo-site
          environment_name: inlimbo-site-env
          version_label: "inlimbo-site-deployment-3"
          region: us-west-1
          deployment_package: deploy.zip
